### ISSUE TITLE
Please enable GitHub Issues on https://github.com/CoreELEC/CoreELEC

### ISSUE THREAD

**Issue by probonopd** [CoreELEC/qca6174-aml#1]
Please enable GitHub Issues on https://github.com/CoreELEC/CoreELEC.

Right now it is diabled and the only way to report an issue seems to be https://discourse.coreelec.org which requires one to set up (create another set of login credentials one has to take care of) with no option to log into the forum using an existing GitHub account.

It would be nice if one would not have to go through all the hassle of signing up to yet another forum just to report an issue for software which is hosted on GitHub.

Thank you very much for your consideration.

**Comment by Portisch** [comment]
When you have a issue with this driver just open one here!?

**Comment by probonopd** [comment]
Actually I have an issue with [CoreELEC](https://github.com/CoreELEC/CoreELEC) most likely unrelated to the qca6174 driver.

**Comment by Raybuntu** [comment]
Please report your issue in our forums.

**Comment by probonopd** [comment]
This is where I have no access to, because I cannot use the forums without having to sign up. The forum does not allow to log in using existing GitHub credentials (SSO). This is very user unfriendly.

Having to sign up for https://discourse.coreelec.org/ defeats the very purpose of this ticket, which is about being able to report issues without having to sign up for yet another forum.

**Comment by vpeter4** [comment]
But we do support only on forum.

**Comment by Raybuntu** [comment]
Well I am sorry for your inconvenience but we are a small team and do not offer a support contract for convenience. We can't have tickets or anything. We rely on volunteers from the community. Of course it is your free will to sign up or not. But remember we are not a company and we do not make any money.

**Comment by Raybuntu** [comment]
But feel free to describe your issue here but just know that it is basically offtopic and we will disable issues for this driver soon.

**Comment by probonopd** [comment]
Thanks for considering my request. Maybe you can enable signle-sign-on (SSO) through GitHub on your forum, so that one could post to the forum without having to deal with yet another username and password.

I like your project a lot and I appreciate the time everyone is putting in as volunteers. :+1:

**Comment by Raybuntu** [comment]
SSO sounds good. I am not aware that there is a GH discourse SSO Integration. Please tell me if I am wrong. We are open to that idea.

**Comment by probonopd** [comment]
There is indeed:

![image](https://user-images.githubusercontent.com/2480569/191085172-99efcbc4-4830-437e-8c2c-374a714689b8.png)

I think Discourse can also do Google and others.

**Comment by Raybuntu** [comment]
I will look into it. Thx

**Comment by ceoath** [comment]
This has been added. The oath app runs with this GitHub account.

**Comment by probonopd** [comment]
Excellent. Thank you very, very much everyone who helped to make this happen. :100:
